#**Dataset das Questões de um Exame para Certificação PMP**
Versão 1.0 20/05/2026
<h2>Mestrando: Pedro Ivo Santos Leite</h2>
<h3>Mestrado Profissional em Tecnologia da Informação</h3>
<h3>Disciplina: 20261 - Ciência dos Dados</h3>

<b>Professores: Alex Sandro da Cunha Rêgo, Damires Yluska Souza Fernandes </b>

A crescente complexidade dos ambientes organizacionais e a necessidade de entrega eficiente de resultados têm ampliado a relevância do gerenciamento de projetos como competência estratégica nas mais diversas áreas de atuação. Nesse contexto, certificações profissionais, como as oferecidas pelo Project Management Institute (PMI), destacam-se como importantes mecanismos de validação de conhecimento, habilidades e competências, sendo amplamente reconhecidas no mercado global. Entre essas certificações, o **Project Management Professional (PMP)** figura como uma das mais valorizadas, exigindo dos candidatos não apenas domínio conceitual, mas também capacidade de aplicação prática em cenários complexos e situacionais.

A versão mais recente do guia do PMI é o PMBOK Guide Seventh Edition, publicada em 2021 pelo Project Management Institute.Essa edição trouxe uma mudança significativa em relação às anteriores: deixou de ser estruturada em processos (como nas versões anteriores) e passou a adotar uma abordagem baseada em princípios e domínios de desempenho, refletindo práticas mais modernas, incluindo métodos ágeis, híbridos e adaptativos. Apesar disso, o exame PMP atual não depende exclusivamente do PMBOK 7, sendo também fortemente baseado no Exam Content Outline (ECO) e em múltiplas referências

A proposta contempla a validação de um dataset público com **1080 questões do PMBOK V7 Guide para compor simulados do exame oficial PMP**, disponibilizado pela empresa **Oliver F. Lehmann**, especializada em treinamentos para gerente de projetos para realizarem o exame PMP.Esta proposta é importante como sendo o primeiro passo rumo à dissertação do mestrado por me proporcionar um entendimento mais profundo dessa importante certificação para os gerente de projetos profissionais.

In [ ]:
# consultando a versão do Python instalado na VM do Colab
!python -V

In [ ]:
# output_file_path = '/content/drive/MyDrive/2026/PMP/pmp_dataset_5000_PRO_unique.csv'
# df_questoes.to_csv(output_file_path, index=False)
# print(f"Dataset salvo em: {output_file_path}")
# This code has been commented out because df_questoes is not defined at this point.
# The operation to save df_questoes will be moved to a cell after its definition (cell szwzUPHFJ8s0).

# Carregamento de Bibliotecas

In [ ]:
import pandas as pd
import numpy as np

# 1. Carga de Dados (Questões do PMBok 7)

In [2]:
from google.colab import drive
import pandas as pd
import re

drive.mount('/content/drive', force_remount=True)

# Caminho completo para o arquivo
# ATENÇÃO: O erro 'FileNotFoundError' indica que o arquivo CSV especificado
# não foi encontrado no caminho. Por favor, verifique se o nome do arquivo
# e o caminho estão EXATAMENTE corretos no seu Google Drive.
# Sugestão baseada nos arquivos disponíveis: '/content/drive/MyDrive/df_questoes_processed.csv'
file_path = '/content/drive/MyDrive/2026/760_questions.csv'
# Exemplo correto (se o nome for esse):
# file_path = '/content/drive/MyDrive/1500 questoes PMP (com explanações).csv'
# Outro exemplo de arquivo CSV de referência do notebook:
# file_path = '/content/drive/MyDrive/2026/PMP/pmp_dataset_5000_PRO_unique.csv'

# Carregando o dataset
df_questoes = pd.read_csv(file_path)

# Exibindo as primeiras linhas
df_questoes.head(3)

Mounted at /content/drive

,id,statement,option1,option2,option3,option4,option5,correct_answer,correct_answers,explanation,erro_alternative1,erro_alternative2,erro_alternative3,erro_alternative4,erro_alternative5,source,keywords
0,464,A project manager is reviewing the tools and t...,All of the following are tools and techniques ...,Risk audits,Technical performance analysis,Reserve analysis,Enhancement analysis,5.0,NaN,Enhancement analysis is NOT a tool or techniqu...,Risk audits examine the effectiveness of risk ...,Technical performance analysis compares techni...,Reserve analysis compares the amount of contin...,NaN,NaN,760_questions.txt,scrum_framework
1,91,A project manager is working with the team to ...,Progressive elaboration,Product analysis,Requirements gathering,Decomposition,NaN,4.0,NaN,Decomposition is the technique of subdividing ...,Progressive elaboration is the iterative proce...,Product analysis involves examining product re...,Requirements gathering collects stakeholder ne...,NaN,NaN,760_questions.txt,"linhas_de_base, scrum_framework"
2,500,A project manager is preparing for a major pro...,Ensure all potential sellers have a clear and ...,Provide an opportunity for sellers to ask ques...,Address any ambiguities or uncertainties in th...,Select the seller who is best capable of offer...,NaN,4.0,NaN,A bidding conference (also called a bidder con...,Ensuring all potential sellers have clear and ...,Providing opportunity for sellers to ask quest...,Addressing ambiguities or uncertainties in pro...,NaN,NaN,760_questions.txt,scrum_framework

In [ ]:
df_questoes

,id,statement,option1,option2,option3,option4,option5,correct_answer,correct_answers,explanation,erro_alternative1,erro_alternative2,erro_alternative3,erro_alternative4,erro_alternative5,source
0,464,A project manager is reviewing the tools and t...,All of the following are tools and techniques ...,Risk audits,Technical performance analysis,Reserve analysis,Enhancement analysis,5.0,NaN,Enhancement analysis is NOT a tool or techniqu...,Risk audits examine the effectiveness of risk ...,Technical performance analysis compares techni...,Reserve analysis compares the amount of contin...,NaN,NaN,760_questions.txt
1,91,A project manager is working with the team to ...,Progressive elaboration,Product analysis,Requirements gathering,Decomposition,NaN,4.0,NaN,Decomposition is the technique of subdividing ...,Progressive elaboration is the iterative proce...,Product analysis involves examining product re...,Requirements gathering collects stakeholder ne...,NaN,NaN,760_questions.txt
2,500,A project manager is preparing for a major pro...,Ensure all potential sellers have a clear and ...,Provide an opportunity for sellers to ask ques...,Address any ambiguities or uncertainties in th...,Select the seller who is best capable of offer...,NaN,4.0,NaN,A bidding conference (also called a bidder con...,Ensuring all potential sellers have clear and ...,Providing opportunity for sellers to ask quest...,Addressing ambiguities or uncertainties in pro...,NaN,NaN,760_questions.txt
3,527,A project manager is reviewing the stakeholder...,Stakeholder influence level and interest in pr...,Stakeholder requirements and expectations for ...,Specific communication methods and frequency f...,Stakeholder classification as internal or exte...,NaN,3.0,NaN,"Communication methods, frequency, and detailed...",Influence level and interest are core assessme...,Requirements and expectations are essential st...,NaN,Classification as internal or external is basi...,NaN,760_questions.txt
4,578,One of your team members is concerned about a ...,Work with the team member to find ways to acce...,"To avoid delays, reprioritize the iteration ba...",Document the delay and adjust the project sche...,Assign additional team members to the delayed ...,NaN,2.0,NaN,When a key task with dependencies will be dela...,Working with the team member to accelerate the...,NaN,Documenting the delay and adjusting the schedu...,Assigning additional team members to the delay...,NaN,760_questions.txt
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1003,493,A project manager wants to implement process i...,Direct and Manage Project Work,Monitor and Control Project Work,Develop Project Management Plan,Perform Integrated Change Control,NaN,1.0,NaN,Direct and Manage Project Work is the executin...,NaN,NaN,NaN,NaN,NaN,760_questions.txt
1004,243,Towards the end of a large-scale infrastructur...,Initiate an intensive quality assurance traini...,Bring in an external consultant with expertise...,Facilitate a problem-solving session to tackle...,Allocate additional time specifically for qual...,NaN,2.0,NaN,With limited time before deadline and a signif...,Initiating intensive training diverts the team...,NaN,Facilitating a problem-solving session delays ...,Allocating additional schedule time for QA con...,NaN,760_questions.txt
1005,394,Which of the following is a valid formula for ...,EAC = AC + (BAC - EV),EAC = BAC / CPI,EAC = AC + Bottom-up ETC,EAC = AC + \[(BAC - EV) / CPI\],All of the above,5.0,NaN,There are four widely recognized valid formula...,NaN,NaN,NaN,NaN,NaN,760_questions.txt
1006,368,A project manager is actively managing the rel...,Plan Sourcing Strategy,Conduct Procurements,Control Procurements,Close Procurements,NaN,3.0,NaN,Control Procurements is the process of managin...,Plan Sourcing Strategy occurs during planning ...,Conduct Procurements focuses on obtaining prop...,NaN,Close Procurements finalizes contracts after w...,NaN,760_questions.txt
1007,184,In the early stages of a new mobile applicatio...,Pre-allocate additional time buffers in the pr...,Outsource the development of the most complex ...,Conduct a preliminary risk assessment solely f...,Increase the frequency of project status meeti...,NaN,1.0,NaN,Pre-allocating time buffers (schedule continge...,NaN,Outsourcing complex features to specialized fi...,Conducting a preliminary risk assessment focus...,Increasing status meeting frequency improves m...,NaN,760_questions.txt

# 2. Customizando o Dataset com novas colunas

# 2.1 Criação as colunas Dominio e Approach

In [ ]:
import re

GATILHOS_DOMINIO = {
    'Ambiente de Negocios': r'(conformidade|compliance|regulamenta| lei |legal|diretriz|estrategia|business case|beneficio|governança|esg|sustentabilidade|mercado|concorrencia)',
    'Pessoas': r'(conflito|disputa|discussao|briga|membro|equipe|time|stakeholder|partes interessadas|motiva|desmoti|lider|servidor|remoto|virtual|gerente funcional|emocional)',
    # NOVO: Lista explícita para o domínio de Processos
    'Processos': r'(cronograma|orçamento|custo|escopo|qualidade|risco|aquisiç|mudança|ccb|baseline|linha de base|sprint|backlog|burndown|caminho critico|estimativa|cpi|spi)'
}

# 1. FUNÇÃO DE LOGICA DE DOMINIO:Classificação da coluna

def classificar_dominio(texto):
    texto = str(texto).lower()

    if re.search(GATILHOS_DOMINIO['Ambiente de Negocios'], texto):
        return 'Ambiente de Negocios'

    if re.search(GATILHOS_DOMINIO['Pessoas'], texto):
        return 'Pessoas'

    if re.search(GATILHOS_DOMINIO['Processos'], texto):
        return 'Processos'

    # Caso não ache absolutamente nada, mantém um fallback genérico
    return 'Processos'

#2. FUNÇÃO DE LOGICA DE APPROACH: Classificação da coluna APPROACH

GATILHOS_APPROACH = {
    # NOVO: Gatilhos dedicados ao mundo Preditivo / Cascata
    'Preditivo': r'(preditivo|cascata|waterfall|linha de base|baseline|plano de gerenciamento|ccb|comitê de mudança|solicitação formal|caminho critico|critical path|gantt|eap|wbs|contrato rigido|escopo fechado)',

    'Agil': r'( sprint|iteraç|backlog|user stor|historia de usuario|product owner| scrum|kanban|daily|diaria|retrospectiva|review|lider servidor|servant|auto-organiza|burndown|burnup|mvp|ondas sucessivas)',

    'Hibrido': r'(hibrido|hybrid|misto|equipe de desenvolvimento usa scrum mas|engenharia e cascata mas o software)'
}

def classificar_approach(texto):
    texto = str(texto).lower()

    # 1. Checa primeiro cenários de choque metodológico (Híbridos)
    if re.search(GATILHOS_APPROACH['Hibrido'], texto):
        return 'Hibrido'

    # 2. Checa de forma ativa os termos do universo Ágil
    if re.search(GATILHOS_APPROACH['Agil'], texto):
        return 'Agil'

    # 3. NOVO: Checa de forma ativa os termos tradicionais / preditivos
    if re.search(GATILHOS_APPROACH['Preditivo'], texto):
        return 'Preditivo'

    # Fallback caso o enunciado não mencione ferramentas ou metodologias diretas
    return 'Preditivo'  # Ou 'Agil', dependendo da maioria do seu dataset

In [ ]:
# 3. APLICAÇÃO NO SEU DATASET
# Substitua pelo caminho do seu arquivo (csv, xlsx, etc.)
# df = pd.read_csv("seu_dataset.csv")

# Exemplo de simulado para teste:
dados_exemplo = {
    'questao': [
        "Um membro da equipe e o lider tecnico estao em conflito sobre as tarefas da proxima entrega.",
        "O governo aprovou uma nova lei de conformidade que afeta a segurança do produto.",
        """Durante a Sprint 3, o Product Owner pediu para alterar o
Backlog.""", # Fixed SyntaxError here
        "O gerente de projetos esta controlando o desvio do caminho critico usando o cronograma.",
        "A equipe de software usa Scrum, mas o PMO exige relatorios mensais em graficos de Gantt."
    ]
}
df = pd.DataFrame(dados_exemplo)

# Aplicando a lógica nas colunas do DataFrame de exemplo
df['dominio'] = df['questao'].apply(classificar_dominio)
df['approach'] = df['questao'].apply(classificar_approach)

# Visualizando o resultado do DataFrame de exemplo
print(df[['questao', 'dominio', 'approach']])

                                             questao               dominio  \
0  Um membro da equipe e o lider tecnico estao em...               Pessoas
1  O governo aprovou uma nova lei de conformidade...  Ambiente de Negocios
2  Durante a Sprint 3, o Product Owner pediu para...             Processos
3  O gerente de projetos esta controlando o desvi...             Processos
4  A equipe de software usa Scrum, mas o PMO exig...               Pessoas

    approach
0  Preditivo
1  Preditivo
2       Agil
3  Preditivo
4       Agil

# 2.2 Criação da coluna SPLIT.

Para criar a coluna split dividindo o seu dataset de forma correta e aleatória entre os três conjuntos tradicionais de Machine Learning (Treino, Validação e Teste), o método mais seguro e robusto é utilizar a função train_test_split da biblioteca sklearn aplicada duas vezes. Isso garante que a proporção escolhida seja respeitada com precisão. O padrão mais recomendado para projetos desse tipo é 70% para Treino, 15% para Validação e 15% para Teste.

In [ ]:
from sklearn.model_selection import train_test_split

# ==============================================================================
# 1. SIMULAÇÃO DO SEU DATASET (Substitua pela leitura do seu CSV real)
# ==============================================================================
# Exemplo simulando que você já carregou seu df com enunciados e alternativas
# df = pd.read_csv("seu_arquivo_pmp.csv")
np.random.seed(42)  # Garante reprodutibilidade
dados_exemplo = {
    "enunciado": [f"Questão PMP situacional número {i}" for i in range(100)],
    "opcao_A": [f"Alternativa A da questão {i}" for i in range(100)],
    "opcao_B": [f"Alternativa B da questão {i}" for i in range(100)],
    "opcao_C": [f"Alternativa C da questão {i}" for i in range(100)],
    "opcao_D": [f"Alternativa D da questão {i}" for i in range(100)]
}
df = pd.DataFrame(dados_exemplo)

# ==============================================================================
# 2. LÓGICA DE DIVISÃO DOS TRÊS CONJUNTOS (70% / 15% / 15%)
# ==============================================================================

# Passo 1: Separamos primeiro os 70% de Treino. O que sobra (30%) vai para um bloco temporário.
df_train, df_temp = train_test_split(
    df,
    test_size=0.30,        # 30% para o bloco temporário
    random_state=42,       # Garante que o split seja sempre idêntico ao rodar de novo
    shuffle=True           # Embaralha as questões para evitar viés de ordem
)

# Passo 2: Pegamos o bloco temporário (30%) e dividimos exatamente ao meio (0.50).
# Metade de 30% é 15% para validação e 15% para teste.
df_val, df_test = train_test_split(
    df_temp,
    test_size=0.50,        # Divide o bloco temporário ao meio
    random_state=42,
    shuffle=True
)

# ==============================================================================
# 3. MAPEAMENTO E CRIAÇÃO DA COLUNA 'SPLIT' NO DATASET ORIGINAL
# ==============================================================================
# Criamos a nova coluna preenchida com strings indicando o destino de cada linha
df.loc[df_train.index, 'split'] = 'train'
df.loc[df_val.index, 'split'] = 'validation'
df.loc[df_test.index, 'split'] = 'test'

# ==============================================================================
# 4. VALIDAÇÃO DOS RESULTADOS (Print de Conferência)
# ==============================================================================
print("--- DISTRIBUIÇÃO DA COLUNA SPLIT ---")
print(df['split'].value_counts())
print("\nPorcentagem de cada conjunto:")
print(df['split'].value_counts(normalize=True) * 100)

# Exemplo visual das primeiras linhas do seu novo dataset estruturado
df.head()

--- DISTRIBUIÇÃO DA COLUNA SPLIT ---
split
train         70
test          15
validation    15
Name: count, dtype: int64

Porcentagem de cada conjunto:
split
train         70.0
test          15.0
validation    15.0
Name: proportion, dtype: float64

,enunciado,opcao_A,opcao_B,opcao_C,opcao_D,split
0,Questão PMP situacional número 0,Alternativa A da questão 0,Alternativa B da questão 0,Alternativa C da questão 0,Alternativa D da questão 0,test
1,Questão PMP situacional número 1,Alternativa A da questão 1,Alternativa B da questão 1,Alternativa C da questão 1,Alternativa D da questão 1,train
2,Questão PMP situacional número 2,Alternativa A da questão 2,Alternativa B da questão 2,Alternativa C da questão 2,Alternativa D da questão 2,train
3,Questão PMP situacional número 3,Alternativa A da questão 3,Alternativa B da questão 3,Alternativa C da questão 3,Alternativa D da questão 3,train
4,Questão PMP situacional número 4,Alternativa A da questão 4,Alternativa B da questão 4,Alternativa C da questão 4,Alternativa D da questão 4,test

# 2.3 Criar a coluna question_lenght
Para criar uma nova coluna que calcula o comprimento do enunciado da questão (Question Length), você pode usar a função .str.len() do pandas. Essa métrica é excelente para modelos de NLP, pois ajuda a analisar se o modelo performa melhor em questões curtas (diretas) ou longas (situacionais).

In [ ]:
# Simulação do DataFrame baseado no histórico que estamos construindo:

dados_pmp = {
    "enunciado": [
        "Um membro da equipe e o lider tecnico estao em conflito severo sobre a arquitetura do software, atrasando a entrega.",
        "Uma nova regulamentacao de conformidade ambiental entrou em vigor. Quais as DUAS primeiras acoes que o gerente de projetos deve tomar?",
        "O cliente solicitou uma mudanca drastica de escopo no meio do projeto preditivo. O que fazer?"
    ],
    "split": ["train", "validation", "test"]
}
df = pd.DataFrame(dados_pmp)

# ==============================================================================
# 2. CRIANDO A COLUNA DE COMPRIMENTO (QUESTION LENGTH)
# ==============================================================================

# Garante que todo o conteúdo da coluna seja tratado como texto (string) antes de medir
df['enunciado'] = df['enunciado'].astype(str)

# Cria a coluna com a contagem total de caracteres (incluindo espaços)
df['question_length'] = df['enunciado'].str.len()

# (Opcional) Se você quiser contar o número de PALAVRAS em vez de caracteres:
# df['question_word_count'] = df['enunciado'].apply(lambda x: len(x.split()))

# ==============================================================================
# 3. CONFERINDO O RESULTADO
# ==============================================================================
print("--- DATASET ATUALIZADO ---")
print(df[['enunciado', 'question_length', 'split']])

# Uma análise estatística rápida do tamanho das suas questões
print("\n--- RESUMO ESTATÍSTICO DO COMPRIMENTO ---")
print(df['question_length'].describe())

--- DATASET ATUALIZADO ---
                                           enunciado  question_length  \
0  Um membro da equipe e o lider tecnico estao em...              116
1  Uma nova regulamentacao de conformidade ambien...              134
2  O cliente solicitou uma mudanca drastica de es...               93

        split
0       train
1  validation
2        test

--- RESUMO ESTATÍSTICO DO COMPRIMENTO ---
count      3.000000
mean     114.333333
std       20.550750
min       93.000000
25%      104.500000
50%      116.000000
75%      125.000000
max      134.000000
Name: question_length, dtype: float64

# 2.4 Criar a coluna Difficulty
Para criar uma coluna de Dificuldade (Difficulty) de forma automatizada no seu dataset de PMP, a estratégia mais inteligente é construir uma heurística (um motor de regras) baseada em duas variáveis que já extraímos: o Comprimento do Enunciado (question_length) e o Approach (approach).

No exame PMP, as questões mais difíceis são as Híbridas (pois exigem transição de mentalidade) e as Situacionais Longas (com enunciados grandes que cansam o candidato e escondem pegadinhas). As questões mais fáceis são as Preditivas Curtas (que costumam ser mais diretas sobre processos ou ferramentas).

**"Por que eu usar o *Approach* para calcular a coluna de dificuldade do meu modelo?"**

No universo do PMI, a abordagem escolhida (`approach`) mexe diretamente com a **complexidade interpretativa** da questão. Não é só o tamanho do texto que cansa, é o tipo de problema que o modelo precisa resolver.

Aqui está a lógica do porquê o *Approach* é um excelente termômetro para definir a dificuldade:

---

## 2.4.1. O Peso Cognitivo de cada Approach

Se o seu modelo avaliar a dificuldade olhando apenas para o tamanho do texto, ele vai errar. O *approach* traz o peso da complexidade das regras:

* **Preditivo (Dificuldade Base: Baixa/Média):** As regras do mundo tradicional são muito pretas no branco. Se houve mudança $\rightarrow$ vai para o CCB. Se o risco aconteceu $\rightarrow$ aplica a resposta ao risco. O modelo decora essas regras de processo facilmente.
* **Ágil (Dificuldade Base: Média):** Exige uma virada de chave para a "Liderança Servidora". O modelo precisa entender que o gerente não manda, ele apoia. A complexidade aqui é entender a dinâmica do time.
* **Híbrido (Dificuldade Base: Alta):** É o cenário mais difícil da prova. A questão coloca o modelo em um cabo de guerra: de um lado um cliente exigindo um cronograma fixo (Preditivo) e do outro um time desenvolvendo em Sprints (Ágil). O modelo precisa encontrar uma resposta que equilibre os dois mundos sem quebrar as regras de nenhum deles.

---

## 2.4.2. A Matriz de Dificuldade do PMP

Ao cruzar o comprimento do texto (`question_length`) com o `approach`, criamos um mapeamento bidimensional muito mais inteligente para o seu dataset. Veja como esses dois eixos interagem:

| Comprimento do Texto (`question_length`) | Approach Preditivo | Approach Ágil | Approach Híbrido |
| --- | --- | --- | --- |
| **Curto** (Direto ao ponto) | 🟢 **Baixa** (Decoreba de processo) | 🟢 **Baixa/Média** (Ação rápida do time) | 🟡 **Média** (Conflito curto de regras) |
| **Médio** (Cenário padrão) | 🟡 **Média** (Análise de impacto) | 🟡 **Média** (Problema com stakeholder) | 🔴 **Alta** (Sempre exige malabarismo) |
| **Longo** (Textão situacional) | 🔴 **Alta** (Esconde a pegadinha no texto) | 🔴 **Alta** (Cenário humano complexo) | 💀 **Muito Alta** (O terror dos candidatos) |

---

## 2.4.3. O Benefício Prático para o Treinamento do Modelo

Ao usar o *approach* para calcular essa dificuldade, você ajuda o seu modelo a se autoavaliar durante o treino:

1. **Segmentação de Performance:** Você poderá filtrar seu dataset de validação para ver o comportamento do modelo: *"Meu modelo tem 95% de acurácia em questões fáceis (Preditivas), mas despenca para 50% nas difíceis (Híbridas)"*.
2. **Ajuste de Pesos (Loss Weighting):** Se você notar que o modelo está errando muito as questões de dificuldade **Alta**, você pode configurar a função de perda (*loss*) do seu treino para dar um peso maior a essas linhas, forçando a rede neural a aprender cenários complexos com mais atenção.

In [ ]:
# ==============================================================================
# 1. SIMULAÇÃO DO DATASET (Substitua pela leitura do seu DataFrame atual)
# ==============================================================================
# O código assume que você já rodou os scripts anteriores e tem as colunas 'approach' e 'question_length'
dados_pmp = {
    "enunciado": [
        "Um recurso chave errou o codigo na Sprint. O que fazer?", # Curta, Ágil
        "O cliente solicitou uma mudanca drastica de escopo no meio do projeto preditivo. O que fazer?", # Média, Preditiva
        "A equipe de software usa Scrum e esta na Sprint 3, mas o departamento de infraestrutura segue o modelo cascata tradicional e atrasou a entrega do servidor homologado, impactando o cronograma geral e gerando um conflito severo entre o Product Owner e o Diretor de Operacoes. Como o gerente de projetos deve agir para alinhar a governanca e resolver o conflito?" # Longa, Híbrida
    ],
    "approach": ["Agil", "Preditivo", "Hibrido"],
    "question_length": [53, 93, 314] # Calculado pelo str.len()
}
df = pd.DataFrame(dados_pmp)

# ==============================================================================
# 2. LÓGICA DE DEFINIÇÃO DA DIFICULDADE
# ==============================================================================

def calcular_dificuldade(row):
    length = row['question_length']
    approach = row['approach']

    # REGRA DE ALTA DIFICULDADE:
    # Questões Híbridas (independente do tamanho) OU qualquer questão muito longa (Ex: mais de 200 caracteres)
    if approach == 'Hibrido' or length > 200:
        return 'Alta'

    # REGRA DE MÉDIA DIFICULDADE:
    # Questões Ágeis/Preditivas com tamanho intermediário (entre 80 e 200 caracteres)
    elif 80 <= length <= 200:
        return 'Media'

    # REGRA DE BAIXA DIFICULDADE:
    # Questões curtas (menos de 80 caracteres) de abordagem direta (Ágil ou Preditiva)
    else:
        return 'Baixa'

# Aplica a função linha por linha criando a nova coluna
df['difficulty'] = df.apply(calcular_dificuldade, axis=1)

# ==============================================================================
# 3. CONFERINDO A DISTRIBUIÇÃO
# ==============================================================================
print("--- DATASET COM COLUNA DE DIFICULDADE ---")
print(df[['approach', 'question_length', 'difficulty']])

print("\n--- QUANTIDADE POR NÍVEL DE DIFICULDADE ---")
print(df['difficulty'].value_counts())

--- DATASET COM COLUNA DE DIFICULDADE ---
    approach  question_length difficulty
0       Agil               53      Baixa
1  Preditivo               93      Media
2    Hibrido              314       Alta

--- QUANTIDADE POR NÍVEL DE DIFICULDADE ---
difficulty
Baixa    1
Media    1
Alta     1
Name: count, dtype: int64

# 2.5 Criar acoluna Keywords
Para criar a coluna keywords (palavras-chave) de forma eficiente para o seu modelo de Machine Learning, a melhor estratégia é cruzar as listas de gatilhos que já estruturamos para o **Domínio** e para o **Approach**.

Em vez de extrair palavras aleatórias do texto (como "projeto", "gerente", etc.), o código vai escanear o enunciado e salvar apenas os termos técnicos de alto impacto do PMI que ele encontrar. Isso cria uma coluna limpa, padronizada e extremamente útil para o aprendizado da sua rede neural.

🌟 Por que a coluna **keywords** vai ajudar muito o seu modelo?

a. Redução de Ruído: Em vez de forçar o seu modelo a ler um "textão" de 400 caracteres cheio de conectivos (como “e”, “de”, “para”), a coluna keywords entrega um resumo mastigado dos conceitos técnicos puros envolvidos naquela linha (ex: conflito, equipe, mudança).

b. Engenharia de Prompt Robusta: Na hora do treinamento do RoBERTa ou BERT, você pode usar uma técnica chamada feature concatenation para juntar todas essas metatags estruturadas no input do modelo.

In [ ]:
from google.colab import files

# ==============================================================================
# 1. CENTRALIZAÇÃO DE TODOS OS GATILHOS TÉCNICOS DO PMP
# ==============================================================================
DICIONARIO_KEYWORDS = {
    # Ambiente de Negócios
    'conformidade': r'(conformidade|compliance|regulamenta|lei|legal|diretriz)',
    'estratégia': r'(estrategia|business case|beneficio|governança|esg|sustentabilidade|mercado|concorrencia)',
    # Pessoas
    'conflito': r'(conflito|disputa|discussao|briga)',
    'equipe': r'(membro|equipe|time|remoto|virtual|gerente funcional)',
    'stakeholder': r'(stakeholder|partes interessadas|patrocinador|sponsor|cliente)',
    'liderança_servidora': r'(lider servidor|servant|motiva|desmoti|emocional)',
    # Preditivo / Processos
    'mudança': r'(mudança|ccb|comitê de mudança|solicitaç)',
    'linhas_de_base': r'(linha de base|baseline|escopo|cronograma|orçamento|custo|qualidade|aquisiç)',
    'caminho_crítico': r'(caminho critico|critical path|gantt|eap|wbs|estimativa|cpi|spi|risco)',
    # Ágil / Híbrido
    'scrum_framework': r'(sprint|backlog|product owner|po|scrum|kanban|daily|diaria|retrospectiva|review)',
    'entrega_ágeis': r'(user stor|historia de usuario|mvp|ondas sucessivas|auto-organiza|burndown|burnup)',
    'híbrido': r'(hibrido|hybrid|misto|transiç)'
}

# ==============================================================================
# 2. FUNÇÃO PARA EXTRAIR AS KEYWORDS ENCONTRADAS
# ==============================================================================
def extrair_keywords(texto):
    texto = str(texto).lower()
    keywords_encontradas = []

    # Varre o dicionário e adiciona a "tag" se o padrão regex for encontrado no texto
    for tag, regex in DICIONARIO_KEYWORDS.items():
        if re.search(regex, texto):
            keywords_encontradas.append(tag)

    # Junta as palavras-chave por vírgula. Se não achar nenhuma, marca como 'geral'
    return ", ".join(keywords_encontradas) if keywords_encontradas else "geral"

# ==============================================================================
# 3. APLICAÇÃO NO DATASET E SALVAMENTO DO ARQUIVO
# ==============================================================================
# (Simulação do seu DataFrame atualizado com os passos anteriores)
dados_pmp = {
    "enunciado": [
        "Um membro da equipe e o lider tecnico estao em conflito severo sobre a arquitetura do software, atrasando a entrega.",
        "Uma nova regulamentacao de conformidade ambiental entrou em vigor. Quais as primeiras acoes o GP deve tomar?",
        "A equipe de software usa Scrum e esta na Sprint 3, mas o cliente solicitou uma mudanca drastica."
    ],
    "dominio": ["Pessoas", "Ambiente de Negocios", "Processos"],
    "approach": ["Agil", "Preditivo", "Hibrido"],
    "question_length": [116, 114, 98],
    "difficulty": ["Media", "Media", "Alta"],
    "split": ["train", "validation", "test"]
}
df = pd.DataFrame(dados_pmp)

# Criando a nova coluna de palavras-chave
df['keywords'] = df['enunciado'].apply(extrair_keywords)

print("--- VISUALIZAÇÃO DO DATASET COM KEYWORDS ---")
print(df[['enunciado', 'keywords']])

# 4. SALVANDO E BAIXANDO O ARQUIVO DEFINITIVO
nome_do_arquivo = "dataset_pmp_completo_com_keywords.csv"
df.to_csv(nome_do_arquivo, index=False, encoding='utf-8-sig')

print(f"\n✅ Tudo pronto! Arquivo '{nome_do_arquivo}' salvo com sucesso.")
files.download(nome_do_arquivo)

--- VISUALIZAÇÃO DO DATASET COM KEYWORDS ---
                                           enunciado  \
0  Um membro da equipe e o lider tecnico estao em...
1  Uma nova regulamentacao de conformidade ambien...
2  A equipe de software usa Scrum e esta na Sprin...

                               keywords
0                      conflito, equipe
1                          conformidade
2  equipe, stakeholder, scrum_framework

✅ Tudo pronto! Arquivo 'dataset_pmp_completo_com_keywords.csv' salvo com sucesso.

# 2.5.1 Aplicação da Geração de Palavras-chave (`keywords`)`

Agora que a função `extrair_keywords` foi definida, vamos aplicá-la à coluna `statement` do nosso DataFrame principal, `df_questoes`, para criar a coluna `keywords`. Isso permitirá que essa feature seja utilizada em análises futuras e esteja presente no dataset salvo.

In [ ]:
# Aplica a função `extrair_keywords` à coluna 'statement' para criar a coluna 'keywords'
df_questoes['keywords'] = df_questoes['statement'].apply(extrair_keywords)

print("Coluna 'keywords' adicionada a df_questoes com sucesso.")

# Exibe a distribuição da nova coluna para verificação
print("\nDistribuição da coluna 'keywords' (Top 10):")
display(df_questoes['keywords'].value_counts().head(10))

# Exibe as primeiras linhas com as novas colunas para conferência
display(df_questoes[['statement', 'keywords']].head())

Coluna 'keywords' adicionada a df_questoes com sucesso.

Distribuição da coluna 'keywords' (Top 10):

keywords
geral                                      349
scrum_framework                            279
stakeholder, scrum_framework                79
stakeholder                                 38
equipe                                      34
equipe, scrum_framework                     30
linhas_de_base                              21
caminho_crítico, scrum_framework            18
linhas_de_base, scrum_framework             17
equipe, linhas_de_base, scrum_framework     15
Name: count, dtype: int64

,statement,keywords
0,A project manager is reviewing the tools and t...,scrum_framework
1,A project manager is working with the team to ...,"linhas_de_base, scrum_framework"
2,A project manager is preparing for a major pro...,scrum_framework
3,A project manager is reviewing the stakeholder...,"stakeholder, scrum_framework"
4,One of your team members is concerned about a ...,caminho_crítico

# 2.5.2 Salvar o `df_questoes` Atualizado com a Coluna `keywords`

Com todas as novas colunas (`split`, `dominio`, `approach`, `question_length`, `difficulty`, `correct_answer_letters`, `keywords`) adicionadas e processadas, é crucial salvar o DataFrame `df_questoes` para persistir todas as modificações. Isso garante que não perderemos o trabalho realizado e que o dataset esteja pronto para as próximas etapas, como o treinamento de modelos de Machine Learning.

In [ ]:
# Definindo o caminho completo para salvar o arquivo CSV no Google Drive
output_file_path = '/content/drive/MyDrive/2026/760_questions.csv'

# Salvando o DataFrame atualizado em um novo arquivo CSV, sem o índice do pandas
df_questoes.to_csv(output_file_path, index=False)

print(f"✅ DataFrame 'df_questoes' atualizado e salvo com sucesso em: {output_file_path}")

✅ DataFrame 'df_questoes' atualizado e salvo com sucesso em: /content/drive/MyDrive/2026/760_questions.csv

In [ ]:
df_questoes

,id,statement,option1,option2,option3,option4,option5,correct_answer,correct_answers,explanation,erro_alternative1,erro_alternative2,erro_alternative3,erro_alternative4,erro_alternative5,source,keywords
0,464,A project manager is reviewing the tools and t...,All of the following are tools and techniques ...,Risk audits,Technical performance analysis,Reserve analysis,Enhancement analysis,5.0,NaN,Enhancement analysis is NOT a tool or techniqu...,Risk audits examine the effectiveness of risk ...,Technical performance analysis compares techni...,Reserve analysis compares the amount of contin...,NaN,NaN,760_questions.txt,scrum_framework
1,91,A project manager is working with the team to ...,Progressive elaboration,Product analysis,Requirements gathering,Decomposition,NaN,4.0,NaN,Decomposition is the technique of subdividing ...,Progressive elaboration is the iterative proce...,Product analysis involves examining product re...,Requirements gathering collects stakeholder ne...,NaN,NaN,760_questions.txt,"linhas_de_base, scrum_framework"
2,500,A project manager is preparing for a major pro...,Ensure all potential sellers have a clear and ...,Provide an opportunity for sellers to ask ques...,Address any ambiguities or uncertainties in th...,Select the seller who is best capable of offer...,NaN,4.0,NaN,A bidding conference (also called a bidder con...,Ensuring all potential sellers have clear and ...,Providing opportunity for sellers to ask quest...,Addressing ambiguities or uncertainties in pro...,NaN,NaN,760_questions.txt,scrum_framework
3,527,A project manager is reviewing the stakeholder...,Stakeholder influence level and interest in pr...,Stakeholder requirements and expectations for ...,Specific communication methods and frequency f...,Stakeholder classification as internal or exte...,NaN,3.0,NaN,"Communication methods, frequency, and detailed...",Influence level and interest are core assessme...,Requirements and expectations are essential st...,NaN,Classification as internal or external is basi...,NaN,760_questions.txt,"stakeholder, scrum_framework"
4,578,One of your team members is concerned about a ...,Work with the team member to find ways to acce...,"To avoid delays, reprioritize the iteration ba...",Document the delay and adjust the project sche...,Assign additional team members to the delayed ...,NaN,2.0,NaN,When a key task with dependencies will be dela...,Working with the team member to accelerate the...,NaN,Documenting the delay and adjusting the schedu...,Assigning additional team members to the delay...,NaN,760_questions.txt,caminho_crítico
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1003,493,A project manager wants to implement process i...,Direct and Manage Project Work,Monitor and Control Project Work,Develop Project Management Plan,Perform Integrated Change Control,NaN,1.0,NaN,Direct and Manage Project Work is the executin...,NaN,NaN,NaN,NaN,NaN,760_questions.txt,scrum_framework
1004,243,Towards the end of a large-scale infrastructur...,Initiate an intensive quality assurance traini...,Bring in an external consultant with expertise...,Facilitate a problem-solving session to tackle...,Allocate additional time specifically for qual...,NaN,2.0,NaN,With limited time before deadline and a signif...,Initiating intensive training diverts the team...,NaN,Facilitating a problem-solving session delays ...,Allocating additional schedule time for QA con...,NaN,760_questions.txt,equipe
1005,394,Which of the following is a valid formula for ...,EAC = AC + (BAC - EV),EAC = BAC / CPI,EAC = AC + Bottom-up ETC,EAC = AC + \[(BAC - EV) / CPI\],All of the above,5.0,NaN,There are four widely recognized valid formula...,NaN,NaN,NaN,NaN,NaN,760_questions.txt,geral
1006,368,A project manager is actively managing the rel...,Plan Sourcing Strategy,Conduct Procurements,Control Procurements,Close Procurements,NaN,3.0,NaN,Control Procurements is the process of managin...,Plan Sourcing Strategy occurs during planning ...,Conduct Procurements focuses on obtaining prop...,NaN,Close Procurements finalizes contracts after w...,NaN,760_questions.txt,geral
1007,184,In the early stages of a new mobile applicatio...,Pre-allocate additional time buffers in the pr...,Outsource the development of the most complex ...,Conduct a preliminary risk assessment solely f...,Increase the frequency of project status meeti...,NaN,1.0,NaN,Pre-allocating time buffers (schedule continge...,NaN,Outsourcing complex features to specialized fi...,Conducting a preliminary risk assessment focus...,Increasing status meeting frequency improves m...,NaN,760_questions.txt,scrum_framework

In [ ]:
df_questoes[['dominio','approach','question_length','split','keywords', 'difficulty']].value_counts()

KeyError: "['dominio', 'approach', 'question_length', 'split', 'difficulty'] not in index"

In [ ]:
df_questoes.info()

In [ ]:
df_questoes

**Salvar o novo Arquivo**

In [ ]:
# output_file_path = '/content/drive/MyDrive/2026/760_questions.csv'
# df_questoes.to_csv(output_file_path, index=False)
# print(f"Dataset salvo em: {output_file_path}")

# 3 Análise Exploratoria dos dados: Metadados e Estatísticas

**Resumo visual dos tipos de dados**

| Tipo no Pandas |Exemplo   |Descrição   |
|----------------|----------|------------|
|int64 |42|Inteiros|
|float64|42.5|Decimais|
|bool|True|Lógico|
|object|"texto"|Strings ou mistura de tipos|
|datetime64|2023-12-25|Datas e Horários|
|category|"Nível 1"|Dados repetitivos (rótulos)|


**category:** Por que usar? Em vez de salvar a palavra "Brasil" mil vezes, o Pandas salva o número 0 e mantém um dicionário de mapeamento. **Isso reduz drasticamente o uso de memória em colunas com muitas repetições**.

**Dica de Performance**: Se você sabe que seus números são pequenos, pode converter para int32 ou float32 para **economizar metade da memória**.

In [ ]:
df_questoes.describe()

In [ ]:
# Número de linhas e atributos
df_questoes.shape

In [ ]:
df_questoes.nunique()

### Divisão do Dataset e Aplicação das Classificações

Para preparar o dataset para modelos de Machine Learning, é fundamental dividi-lo em conjuntos de treino, validação e teste. Isso garante que o modelo seja avaliado em dados que nunca viu antes, proporcionando uma estimativa realista de seu desempenho. Além disso, aplicaremos as funções de classificação de 'dominio' e 'approach' após esta divisão, garantindo que essas colunas sejam adicionadas ao DataFrame principal `df_questoes`.

In [ ]:
# from sklearn.model_selection import train_test_split

# np.random.seed(42)  # Garante reprodutibilidade

# # ==============================================================================
# # 1. LÓGICA DE DIVISÃO DOS TRÊS CONJUNTOS (70% / 15% / 15%)
# # ==============================================================================

# # Passo 1: Separamos primeiro os 70% de Treino. O que sobra (30%) vai para um bloco temporário.
# df_train, df_temp = train_test_split(
#     df_questoes,
#     test_size=0.30,        # 30% para o bloco temporário
#     random_state=42,       # Garante que o split seja sempre idêntico ao rodar de novo
#     shuffle=True           # Embaralha as questões para evitar viés de ordem
# )

# # Passo 2: Pegamos o bloco temporário (30%) e dividimos exatamente ao meio (0.50).
# # Metade de 30% é 15% para validação e 15% para teste.
# df_val, df_test = train_test_split(
#     df_temp,
#     test_size=0.50,        # Divide o bloco temporário ao meio
#     random_state=42,
#     shuffle=True
# )

# # ==============================================================================
# # 2. MAPEAMENTO E CRIAÇÃO DA COLUNA 'SPLIT' NO DATASET ORIGINAL
# # ==============================================================================
# # Criamos a nova coluna 'split' preenchida com strings indicando o destino de cada linha
# df_questoes.loc[df_train.index, 'split'] = 'train'
# df_questoes.loc[df_val.index, 'split'] = 'validation'
# df_questoes.loc[df_test.index, 'split'] = 'test'

# # ==============================================================================
# # 3. APLICANDO AS FUNÇÕES DE CLASSIFICAÇÃO 'DOMINIO' E 'APPROACH'
# # ==============================================================================
# # Usamos a coluna 'statement' que é a coluna real de questões do seu CSV.
# df_questoes['dominio'] = df_questoes['statement'].apply(classificar_dominio)
# df_questoes['approach'] = df_questoes['statement'].apply(classificar_approach)

# # ==============================================================================
# # 4. VALIDAÇÃO DOS RESULTADOS (Print de Conferência)
# # ==============================================================================
# print("--- DISTRIBUIÇÃO DA COLUNA SPLIT ---")
# print(df_questoes['split'].value_counts())
# print("\nPorcentagem de cada conjunto:")
# print(df_questoes['split'].value_counts(normalize=True) * 100)

# print("\n--- DISTRIBUIÇÃO DAS CLASSIFICAÇÕES 'DOMINIO' E 'APPROACH' ---")
# display(df_questoes[['dominio','approach']].value_counts())

# # Exemplo visual das primeiras linhas do seu novo dataset estruturado, incluindo as novas colunas
# display(df_questoes.head())

# 3.1 Quantas Questões Corretas?

In [ ]:
#Contagem de valores para uma coluna específica:
df_questoes['correct_answer'].value_counts()

In [ ]:
duplicated_count = df_questoes.duplicated().sum()
print("Quantidade de dados duplicados:", duplicated_count)

# 3.2 Distribuição das Questões Corretas

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

# Contar a ocorrência de cada tipo de questao
distribuicao_tipo_res = df_questoes['correct_answer'].value_counts()

# Criar o gráfico de barras
plt.figure(figsize=(12, 7))
sns.barplot(x=distribuicao_tipo_res.index, y=distribuicao_tipo_res.values, hue=distribuicao_tipo_res.index, palette='viridis', legend=False)
plt.title('Distribuição das Questoes Corretas')
plt.xlabel('Tipo de Dominio')
plt.ylabel('Número de Questões')
plt.xticks(rotation=45, ha='right') # Rotacionar os rótulos do eixo x para melhor legibilidade
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout() # Ajustar o layout para evitar sobreposição
plt.show()

# 3.3 Balanceamento dos Dominios
👉 Ideal: People ~33%, Process ~33%, Business ~33%

In [ ]:
print(df_questoes['dominio'].value_counts(normalize=True))

# 3.4  Balanceamento das Abordagem (APPROACH)
👉 Ideal:Agile / Hybrid / Predictive equilibrados

In [ ]:
print(df_questoes['approach'].value_counts(normalize=True))

# 3.4 Dificuldade das Questões
👉 Ideal: easy / medium / hard equilibrados

In [ ]:
print(df_questoes['difficulty'].value_counts(normalize=True))

In [ ]:
print(df_questoes['keywords'].value_counts(normalize=True))

# 3.5 Distribuição das Respostas
👉 Ideal: A, B, C, D ~25% cada

👉 Problema comum: Muitas respostas “B” → modelo vicia

In [ ]:
print(df_questoes['correct_answer_letters'].value_counts(normalize=True))

### 0. Geração da Coluna `correct_answer_letters`

Para análises que dependem da representação alfabética das respostas corretas (e para resolver o erro no `boxplot`), precisamos criar a coluna `correct_answer_letters`. Esta coluna será populada a partir de `correct_answer` (para respostas únicas) e `correct_answers` (para múltiplas respostas), convertendo os números em letras (1=A, 2=B, etc.).

In [ ]:
# Mapeamento de números para letras de alternativas
# alternative_map = {1: 'A', 2: 'B', 3: 'C', 4: 'D', 5: 'E'}

# def get_correct_answer_letters(row):
#     if pd.notna(row['correct_answers']): # Handle multiple correct answers (e.g., '3,4')
#         # Split by comma, convert to int, map to letter, sort and join
#         num_answers = sorted([int(x.strip()) for x in row['correct_answers'].split(',')])
#         return ','.join([alternative_map.get(num) for num in num_answers if num in alternative_map])
#     elif pd.notna(row['correct_answer']): # Handle single correct answer (e.g., 1.0)
#         return alternative_map.get(int(row['correct_answer']))
#     return np.nan # If no correct answer is specified

# # Aplicar a função para criar a nova coluna
# df_questoes['correct_answer_letters'] = df_questoes.apply(get_correct_answer_letters, axis=1)

# print("Coluna 'correct_answer_letters' criada com sucesso.")
# print("Valores únicos e suas contagens:")
# print(df_questoes['correct_answer_letters'].value_counts(dropna=False))

# 3.6 Métricas dos Tamanhos da Questões

In [ ]:
df_questoes['question_length'] = df_questoes['statement'].apply(len)
print(df_questoes['question_length'].describe())

# 3.7 Boxplot do Tamanhos das Respostas

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

# The 'question_length' column is already created and updated by cell 42f537a1,
# but we re-calculate it here for robustness in case it was overwritten or not run.
df_questoes['question_length'] = df_questoes['statement'].apply(len)

plt.figure(figsize=(10, 6))
sns.boxplot(x='correct_answer_letters', y='question_length', data=df_questoes, palette='viridis', hue='correct_answer_letters', legend=False)
plt.title('Boxplot do Comprimento das Questões por Resposta Correta')
plt.xlabel('Resposta Correta')
plt.ylabel('Comprimento da Questão')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

# 3.8 Qualidade Textual das Questões (detectar dataset artificial)
👉 Muito homogêneo = suspeito (gerado)

In [ ]:
# The 'question_length' column is now calculated within the boxplot cell for robustness.
# This cell's content is no longer needed in its original form.
# print(df_questoes['question_length'].describe())

In [ ]:
# Calcular o IQR para 'question_length'
Q1 = df_questoes['question_length'].quantile(0.25)
Q3 = df_questoes['question_length'].quantile(0.75)
IQR = Q3 - Q1

# Definir os limites para outliers
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# Identificar outliers
outliers = df_questoes[(df_questoes['question_length'] < lower_bound) | (df_questoes['question_length'] > upper_bound)]

print(f"Q1 (25º percentil): {Q1}")
print(f"Q3 (75º percentil): {Q3}")
print(f"IQR: {IQR}")
print(f"Limite Inferior para Outliers: {lower_bound}")
print(f"Limite Superior para Outliers: {upper_bound}")

print(f"\nNúmero de Outliers na 'question_length': {len(outliers)}")

if not outliers.empty:
    print("\nPrimeiras 5 linhas dos Outliers:\n")
    display(outliers.head())
else:
    print("Não foram encontrados outliers na 'question_length'.")

# 3.9 Boxplot do Tamanho das Questões

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10, 6))
sns.boxplot(y='question_length', data=df_questoes)
plt.title('Boxplot do Comprimento das Questões')
plt.ylabel('Comprimento da Questão')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

# 3.10 Questões Duplicatas
👉 Deve ser proximo de zero

In [ ]:
print("Duplicatas:", df_questoes['statement'].duplicated().sum())

In [ ]:
df_questoes["statement"].nunique()

# 3.11 Similaridade das Questões
👉 Se alto → dataset repetitivo

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(df_questoes['statement'])

similarity = cosine_similarity(X)

# pares muito parecidos
threshold = 0.9
duplicates = (similarity > threshold).sum()

print("Alta similaridade:", duplicates)

# 3.11 Avaliação por Split para o Treinamento (fundamental)
👉 Todos os splits devem ter distribuição parecida

In [ ]:
for split in ['train', 'validation', 'test']:
    print("\n", split)
    print(df_questoes[df_questoes['split']==split]['dominio'].value_counts(normalize=True))

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

# Contar a ocorrência de cada tipo de split
distribuicao_split = df_questoes['split'].value_counts()

# Criar o gráfico de barras
plt.figure(figsize=(10, 6))
sns.barplot(x=distribuicao_split.index, y=distribuicao_split.values, hue=distribuicao_split.index, palette='viridis', legend=False)
plt.title('Distribuição de Questões por Split (Treino, Validação, Teste)')
plt.xlabel('Split')
plt.ylabel('Número de Questões')
plt.xticks(rotation=0) # Rótulos horizontais, pois são poucos
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

# 3.11 Score de Qualidade (heurístico)

Interpretação Final

0–1	Fraco
2	Médio
3	Bom

In [ ]:
score = 0

# balanceamento respostas
if df_questoes['correct_answer_letters'].value_counts(normalize=True).std() < 0.05:
    score += 1

# balanceamento domínio
if df_questoes['dominio'].value_counts(normalize=True).std() < 0.1:
    score += 1

# duplicatas
if df_questoes['statement'].duplicated().sum() < 10:
    score += 1

print("Dataset Quality Score:", score, "/ 3")

### 1.10 Análise da Distribuição por Dificuldade

# 3.12 Análise Cruzada de Dificuldade e Domínio

In [ ]:
# Criar tabela de contingência entre 'difficulty' e 'domain'
crosstab_df = pd.crosstab(df_questoes['difficulty'], df_questoes['dominio'])

print("Tabela de Contingência (Dificuldade vs. Domínio):\n")
display(crosstab_df)

# Opcionalmente, pode-se normalizar para ver proporções
print("\nTabela de Contingência Normalizada (proporções por dificuldade):\n")
display(pd.crosstab(df_questoes['difficulty'], df_questoes['dominio'], normalize='index'))

## 3.13 Contagem do Grau de Dificuldade

In [ ]:
# Contagem de valores para a coluna 'difficulty'
distribuicao_dificuldade = df_questoes['difficulty'].value_counts()

print("Distribuição da Dificuldade das Questões:\n", distribuicao_dificuldade)

# Criar o gráfico de barras
plt.figure(figsize=(10, 6))
sns.barplot(x=distribuicao_dificuldade.index, y=distribuicao_dificuldade.values, hue=distribuicao_dificuldade.index, palette='coolwarm', legend=False)
plt.title('Distribuição das Questões por Dificuldade')
plt.xlabel('Nível de Dificuldade')
plt.ylabel('Número de Questões')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

# 4.  Análise Semântica das Questões

Para realizar a análise semântica das questões, podemos usar modelos de *embedding* de sentenças. Esses modelos convertem o texto das perguntas em vetores numéricos de alta dimensão, onde sentenças com significados semelhantes estarão próximas no espaço vetorial.

Usaremos a biblioteca `sentence-transformers` para isso, que provê modelos pré-treinados que são eficazes para capturar o sentido de frases.

In [ ]:
# Instalar a biblioteca sentence-transformers (se ainda não estiver instalada)
!pip install -U sentence-transformers

# 4.1 Carregar Modelo

In [ ]:
from sentence_transformers import SentenceTransformer

# Carregar um modelo pré-treinado para embeddings de sentenças
# 'paraphrase-MiniLM-L6-v2' é um modelo pequeno e eficiente para similaridade de sentenças
# Você pode explorar outros modelos dependendo da sua necessidade (ex: 'all-MiniLM-L6-v2', 'distiluse-base-multilingual-cased-v2' para múltiplos idiomas)
model = SentenceTransformer('paraphrase-MiniLM-L6-v2')

print("Modelo de Sentence-Transformer carregado com sucesso.")

## 4.2 Gerar o Embbeding das Questões

In [ ]:
# Gerar embeddings para a coluna 'question'
# Isso pode levar algum tempo dependendo do tamanho do dataset e do modelo escolhido
print("Gerando embeddings para as questões...")
question_embeddings = model.encode(df_questoes['statement'].tolist(), show_progress_bar=True)

df_questoes['question_embedding'] = question_embeddings.tolist()

print(f"Embeddings gerados. Formato dos embeddings para a primeira questão: {len(df_questoes['question_embedding'].iloc[0])} dimensões.")
# display(df_questoes.head())

# 4.3 Análise Semântica
Agora que temos os embeddings, podemos usá-los para diversas análises semânticas, como:

*   **Encontrar questões semelhantes:** Calculando a similaridade de cosseno entre os vetores.
*   **Agrupamento (Clustering):** Agrupar questões semanticamente similares.
*   **Detecção de anomalias:** Identificar questões que são semanticamente muito diferentes das outras.

Vamos demonstrar como encontrar as questões mais semanticamente similares a uma questão de exemplo.

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

# Escolha uma questão de exemplo para encontrar similares
example_question_index = 0
example_question = df_questoes['statement'].iloc[example_question_index]
example_embedding = question_embeddings[example_question_index]

print(f"Questão de Exemplo ({example_question_index}):\n{example_question}\n")

# Calcular a similaridade de cosseno entre a questão de exemplo e todas as outras questões
similarities = cosine_similarity([example_embedding], question_embeddings)

# Obter os índices das questões mais semelhantes (excluindo a própria questão de exemplo)
similar_indices = similarities.argsort()[0][::-1][1:6] # Top 5 mais similares

print("Top 5 Questões Mais Semelhantes:\n")
for i, idx in enumerate(similar_indices):
    similarity_score = similarities[0][idx]
    question_text = df_questoes['statement'].iloc[idx]
    print(f"  {i+1}. Similaridade: {similarity_score:.4f} - Questão ({idx}): {question_text}\n")

## 4.4 Histograma da Distribuição da Função Cosine

Aqui iremos visualizar a distribuição dos scores de similaridade de cosseno. Primeiro, ele importa as bibliotecas matplotlib.pyplot e seaborn para plotagem. Em seguida, ele 'achata' o array similarities (que foi calculado em uma etapa anterior, provavelmente contendo os scores de similaridade de uma questão contra todas as outras) em um array 1D chamado similarity_scores_flat. É criada uma nova figura com um tamanho especificado. Depois, seaborn.histplot é usado para gerar um histograma desses scores, com bins=50 para definir 50 caixas para a distribuição e kde=True para sobrepor uma curva de Estimativa de Densidade de Kernel. Finalmente, ele define o título e os rótulos para os eixos, adiciona uma grade para legibilidade, ajusta o layout e exibe o gráfico.

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

# Flatten the similarities array for the histogram, or select the relevant row
# The previous 'similarities' array is a 1xN array, so we take the first row.
similarity_scores_flat = similarities[0]

plt.figure(figsize=(10, 6))
sns.histplot(similarity_scores_flat, bins=50, kde=True)
plt.title('Distribution of Cosine Similarity Scores')
plt.xlabel('Cosine Similarity Score')
plt.ylabel('Frequency')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

## **Análise:** Este gráfico é um histograma que mostra a Distribuição dos Scores de Similaridade de Cosine.

O eixo X representa os valores de similaridade de cosseno, que variam de -1 (totalmente dissimilares) a 1 (totalmente similares). Neste caso, os valores observados estão entre aproximadamente 0 e 1, indicando que as questões têm algum grau de similaridade positiva com a questão de exemplo.
O eixo Y mostra a frequência, ou seja, quantas questões caem em cada faixa de similaridade.
A curva azul (KDE - Kernel Density Estimate) suaviza a distribuição e ajuda a visualizar a forma geral dos dados.
Análise:

Observamos que a maioria das questões tem scores de similaridade concentrados em valores mais altos, geralmente acima de 0.6. Isso sugere que a questão de exemplo possui muitas outras questões no dataset que são semanticamente semelhantes a ela. Uma cauda mais longa para a esquerda indicaria que há menos questões muito diferentes. A presença de uma curva com pico mais à direita e caindo para a esquerda indica que há muitas questões com alta similaridade e a quantidade de questões diminui conforme a similaridade baixa.

# 4.5 Identificação dos Pares de Questões Mais Dissimilares

Para encontrar os pares de questões mais dissimilares no dataset, calculamos a similaridade de cosseno entre *todas* as questões e, em seguida, identificamos os pares com os menores valores de similaridade (excluindo a similaridade de uma questão consigo mesma, que sempre será 1).

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

# Calcular a matriz de similaridade de cosseno para todos os pares de questões
# Isso pode ser computacionalmente intensivo para datasets muito grandes
all_pairs_similarities = cosine_similarity(question_embeddings)

# Para encontrar os pares mais dissimilares, precisamos encontrar os valores mínimos na matriz,
# mas devemos ignorar a diagonal (similaridade de uma questão com ela mesma, que é 1).

# Preencher a diagonal com um valor alto para que argsort não a selecione
np.fill_diagonal(all_pairs_similarities, 1.0 + 1e-6) # Valor ligeiramente maior que 1

# Obter os índices dos 5 pares mais dissimilares (menores similaridades)
# Usaremos np.unravel_index para converter os índices planos para 2D

k = 5 # Número de pares mais dissimilares a encontrar
dissimilar_indices_flat = np.argsort(all_pairs_similarities.flatten())[:k*2] # Pegar mais para filtrar duplicatas e a si mesma

# Converter os índices planos de volta para índices 2D (linha, coluna)
dissimilar_pairs_indices = np.unravel_index(dissimilar_indices_flat, all_pairs_similarities.shape)

already_processed_pairs = set()
print(f"Top {k} Pares de Questões Mais Dissimilares:\n")
count = 0
for i, j in zip(dissimilar_pairs_indices[0], dissimilar_pairs_indices[1]):
    # Evitar pares (A,B) e (B,A) e questões com elas mesmas
    if i == j or (j, i) in already_processed_pairs or (i, j) in already_processed_pairs:
        continue

    similarity_score = all_pairs_similarities[i, j]
    question_1 = df_questoes['statement'].iloc[i]
    question_2 = df_questoes['statement'].iloc[j]

    print(f"  {count+1}. Similaridade: {similarity_score:.4f}\n     Questão {i}: {question_1}\n     Questão {j}: {question_2}\n")
    already_processed_pairs.add((i, j))
    count += 1
    if count >= k:
        break

# Resetar a diagonal para o valor original se necessário para análises futuras
np.fill_diagonal(all_pairs_similarities, 1.0)

# 4.6 Agrupamento (Clustering) de Questões por Tópico

Para identificar grupos de questões com tópicos semanticamente similares, podemos aplicar algoritmos de agrupamento (clustering) sobre os *embeddings* das sentenças. Usaremos o algoritmo K-Means, que é popular e eficiente para este tipo de tarefa.

Escolher o número ideal de clusters (K) pode ser um desafio e geralmente requer experimentação ou métodos como o "método do cotovelo" (elbow method). Para começar, vamos definir um número razoável de clusters e depois visualizá-los.

This code performs K-Means clustering to group your questions based on their semantic similarity. First, it defines that 5 clusters should be created. Then, it initializes a K-Means model with 5 clusters, a random_state for reproducibility, and n_init=10 to ensure a robust clustering result by running the algorithm multiple times. Finally, it applies this model to your question_embeddings to assign each question a cluster_label, which is then added as a new column to your df_questoes DataFrame. The print statements then show the results of this clustering, indicating how many questions were assigned to each of the 5 clusters.

In [ ]:
from sklearn.cluster import KMeans
from sklearn.manifold import TSNE
import matplotlib.pyplot as plt
import seaborn as sns

# Definir o número de clusters desejado
num_clusters = 5

# Aplicar K-Means nos embeddings das questões
# random_state para reprodutibilidade
kmeans_model = KMeans(n_clusters=num_clusters, random_state=42, n_init=10)
cluster_labels = kmeans_model.fit_predict(question_embeddings)

# Adicionar os rótulos dos clusters ao DataFrame original
df_questoes['cluster_label'] = cluster_labels

print(f"Agrupamento K-Means concluído com {num_clusters} clusters.")
print("Distribuição dos clusters:")
print(df_questoes['cluster_label'].value_counts().sort_index())

In [ ]:
df_questoes

# 4.7 Visualização dos Clusters

Para visualizar os clusters em 2D, precisamos reduzir a dimensionalidade dos *embeddings* de 384 dimensões. Usaremos o t-SNE (t-Distributed Stochastic Neighbor Embedding) ou PCA para essa finalidade, que são técnicas eficazes para projetar dados de alta dimensão em um espaço de menor dimensão, preservando as relações de similaridade tanto quanto possível.

Os valores de **tsne_x** e **tsne_y** são calculados pela função TSNE da biblioteca sklearn.manifold. O t-SNE (t-Distributed Stochastic Neighbor Embedding) é um algoritmo de redução de dimensionalidade que pega os embeddings de 384 dimensões das suas questões (question_embeddings) e os projeta em um espaço bidimensional (t-SNE Component 1 e t-SNE Component 2) para que possam ser visualizados em um gráfico de dispersão. O objetivo é preservar as relações de proximidade entre os pontos, ou seja, questões que são semanticamente similares no espaço de alta dimensão permanecem próximas no gráfico 2D.

Os novos valores sãoo atualizados no dataset

In [ ]:
# Redução de dimensionalidade para visualização (t-SNE)
# Pode levar algum tempo para datasets grandes
print("Reduzindo dimensionalidade com t-SNE para visualização...")
tsne_model = TSNE(n_components=2, random_state=42, perplexity=30, n_iter=1000)
reduced_embeddings = tsne_model.fit_transform(question_embeddings)

# Adicionar as coordenadas 2D ao DataFrame para plotagem
df_questoes['tsne_x'] = reduced_embeddings[:, 0]
df_questoes['tsne_y'] = reduced_embeddings[:, 1]

plt.figure(figsize=(12, 10))
sns.scatterplot(
    x='tsne_x', y='tsne_y',
    hue='cluster_label',
    palette=sns.color_palette('tab10', num_clusters),
    data=df_questoes,
    legend='full',
    alpha=0.7
)
plt.title(f'Visualização dos Clusters de Questões (t-SNE, K={num_clusters})')
plt.xlabel('t-SNE Component 1')
plt.ylabel('t-SNE Component 2')
plt.grid(True, linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()

**Análise:** Este gráfico é uma visualização dos clusters de questões gerados pelo algoritmo K-Means, utilizando a técnica de Redução de Dimensionalidade t-SNE. O t-SNE é usado para projetar dados de alta dimensão (os embeddings de 384 dimensões) em um espaço 2D, tentando preservar a proximidade de pontos que eram próximos no espaço original.

**Agrupamentos Visuais:** Cada ponto no gráfico representa uma questão, e sua cor indica o cluster ao qual foi atribuída pelo K-Means. O objetivo ideal é ver agrupamentos de cores distintas, indicando que o K-Means conseguiu separar bem os grupos de questões semanticamente similares.

**Dispersão e Densidade:** Áreas onde os pontos de uma mesma cor estão densamente agrupados sugerem que as questões dentro daquele cluster são semanticamente muito próximas. A dispersão dos pontos dentro de um cluster pode indicar a variedade de tópicos abordados por aquele grupo.

**Separação dos Clusters:** Observe a distância e a sobreposição entre os diferentes grupos de cores. Se os clusters estão bem separados, isso significa que o K-Means identificou grupos semanticamente distintos. Se há muita sobreposição entre cores diferentes, pode indicar que as fronteiras entre os clusters não são muito claras, ou que algumas questões possuem similaridade com mais de um tópico principal.

**Outliers/Pontos Isolados:** Pontos de uma cor que estão distantes do seu cluster principal ou misturados com outros clusters podem ser questões que são menos representativas do seu grupo ou que possuem características de múltiplos grupos.

**Em resumo;** o gráfico t-SNE nos permite ter uma percepção visual da qualidade do agrupamento semântico realizado, mostrando o quão bem as questões com tópicos semelhantes foram agrupadas e quão distintas são essas categorias entre si.

In [ ]:
# Definindo o caminho completo para salvar o arquivo CSV no Google Drive, incluindo os novos tse_x e tse_y
output_file_path = '/content/drive/MyDrive/2026/760_questions.csv'

# Salvando o DataFrame atualizado em um novo arquivo CSV, sem o índice do pandas
df_questoes.to_csv(output_file_path, index=False)

print(f"✅ DataFrame 'df_questoes' atualizado e salvo com sucesso em: {output_file_path}")

# 4.8 Análise de Exemplo de Questões por Cluster

Vamos inspecionar algumas questões de cada cluster para entender melhor os tópicos que cada grupo representa.

In [ ]:
for i in range(num_clusters):
    print(f"\n--- Exemplos do Cluster {i} ---")
    cluster_questions = df_questoes[df_questoes['cluster_label'] == i]['statement'].sample(min(3, len(df_questoes[df_questoes['cluster_label'] == i])), random_state=42)
    for j, question in enumerate(cluster_questions):
        print(f"  {j+1}. {question}")

# Exportar dataset para .slsx

In [ ]:
# Substitua pelo caminho do seu arquivo
INPUT_FILE = "/content/drive/MyDrive/2026/760_questions.csv"   # ou .json, .xlsx, etc.
OUTPUT_FILE = "/content/drive/MyDrive/2026/760_question_exportado.xlsx"

# Leitura do arquivo (ajuste conforme o formato)
df = pd.read_csv(INPUT_FILE)         # CSV
# df = pd.read_json(INPUT_FILE)      # JSON
# df = pd.read_excel(INPUT_FILE)     # XLSX existente

# Exporta para Excel
df.to_excel(OUTPUT_FILE, index=False)

print(f"Exportado com sucesso: {OUTPUT_FILE}")

In [ ]:
df_questoes.info()

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

# Calculate the counts of correct answers per domain
domain_answer_counts = df_questoes.groupby(['dominio', 'correct_answer'])['id'].count().unstack(fill_value=0)

# Plotting
domain_answer_counts.plot(kind='bar', figsize=(12, 7), width=0.8)
plt.title('Distribuição de Respostas Corretas por Domínio')
plt.xlabel('Domínio')
plt.ylabel('Número de Questões')
plt.xticks(rotation=45, ha='right')
plt.legend(title='Resposta Correta', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

# Calculate the counts of correct answers per approach
approach_answer_counts = df_questoes.groupby(['approach', 'correct_answer'])['id'].count().unstack(fill_value=0)

# Plotting
approach_answer_counts.plot(kind='bar', figsize=(12, 7), width=0.8)
plt.title('Distribuição de Respostas Corretas por Abordagem')
plt.xlabel('Abordagem')
plt.ylabel('Número de Questões')
plt.xticks(rotation=45, ha='right')
plt.legend(title='Resposta Correta', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

### 3.14 Heatmap de Domínio vs. Abordagem

Este heatmap visualiza a frequência conjunta de questões por `dominio` (domínio) e `approach` (abordagem). Cada célula mostra a contagem de questões que se enquadram em uma combinação específica de domínio e abordagem. Isso ajuda a identificar rapidamente quais combinações são mais comuns no dataset.

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

# Criar uma tabela de contingência (crosstab) entre 'dominio' e 'approach'
contingency_table = pd.crosstab(df_questoes['dominio'], df_questoes['approach'])

plt.figure(figsize=(8, 4))
sns.heatmap(contingency_table, annot=True, fmt='d', cmap='viridis', linewidths=.5)
plt.title('Heatmap de Domínio vs. Abordagem')
plt.xlabel('Abordagem')
plt.ylabel('Domínio')
plt.tight_layout()
plt.show()

O heatmap criado mostra a frequência de questões com base na combinação de 'domínio' e 'abordagem'. Cada célula do gráfico indica o número de questões que se enquadram em um domínio e uma abordagem específicos.

**Interpretação do Heatmap:**

Domínio de Processos: Este domínio concentra o maior número de questões. Ele é predominantemente representado pela abordagem Preditiva (397 questões), seguido pela abordagem Ágil (82 questões). A abordagem 'Híbrido' tem uma presença mínima, com apenas 1 questão neste domínio.

Domínio de Pessoas: Este domínio também apresenta um número significativo de questões, com a abordagem Preditiva sendo a mais comum (178 questões). A abordagem Ágil tem 38 questões, e há 1 questão para 'Híbrido'.

Domínio de Ambiente de Negócios: Este domínio possui o menor número de questões no geral. A abordagem Preditiva responde por 19 questões, enquanto a abordagem Ágil tem 4 questões. Não há questões 'Híbrido' neste domínio.

Observações Gerais:

A abordagem Preditiva é, de longe, a mais dominante em todos os domínios, especialmente nos domínios de 'Processos' e 'Pessoas'.
A abordagem Ágil está presente nos três domínios, mas com um número significativamente menor de questões em comparação com a 'Preditiva'.
A abordagem Híbrido é muito rara, aparecendo em apenas duas questões em todo o conjunto de dados, indicando sua representação mínima.
Este heatmap fornece uma visão clara de como as questões estão distribuídas entre os diferentes domínios e abordagens de gerenciamento de projetos em seu conjunto de dados.

In [ ]:
df_questoes.info()

# Diagnóstico do balanceamento da classe Dominio

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/2026/760_questions.csv")
print(df["dominio"].value_counts())  # substitua "label" pelo nome da sua coluna de classe

In [ ]:
from sklearn.utils import resample
import pandas as pd

# Get the counts of each class in the 'dominio' column
dominio_counts = df["dominio"].value_counts()

# Identify the majority class name and its count
majority_class_name = dominio_counts.idxmax()
majority_count = dominio_counts.max()

# Separate the DataFrame into majority and minority classes
majority_df = df[df["dominio"] == majority_class_name]

# Create a list to store upsampled dataframes for minority classes
upsampled_minority_dfs = []

# Loop through each unique class in 'dominio'
for class_name in dominio_counts.index:
    if class_name != majority_class_name:
        minority_df = df[df["dominio"] == class_name]
        # Upsample the minority class to match the majority count
        minority_upsampled = resample(minority_df,
                                      replace=True,
                                      n_samples=majority_count,
                                      random_state=42)
        upsampled_minority_dfs.append(minority_upsampled)

# Concatenate the majority dataframe with all upsampled minority dataframes
balanced_df = pd.concat([majority_df] + upsampled_minority_dfs)

# Display the new distribution to confirm balancing
print("Distribuição do 'dominio' após balanceamento:")
print(balanced_df['dominio'].value_counts())

# Save the balanced dataframe to a new CSV file
balanced_df.to_csv("dataset_balanced.csv", index=False)
print("Balanced dataset saved to 'dataset_balanced.csv'")

In [ ]:
# Calculate the counts of correct answers per domain
domain_answer_counts = balanced_df.groupby(['dominio', 'correct_answer'])['id'].count().unstack(fill_value=0)

# Plotting
domain_answer_counts.plot(kind='bar', figsize=(12, 7), width=0.8)
plt.title('Distribuição de Respostas Corretas por Domínio Balanceado')
plt.xlabel('Domínio')
plt.ylabel('Número de Questões')
plt.xticks(rotation=45, ha='right')
plt.legend(title='Resposta Correta', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

In [ ]:
balanced_df.info()

# Medir a acuracia com os "dominio" balanceado

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report
from sklearn.ensemble import RandomForestClassifier
import numpy as np
import ast # Import the ast module for literal_eval

# Assuming balanced_df is available from previous cell execution

# 1. Target variable
y = balanced_df["dominio"]

# 2. Select numerical features that can be used directly
# Exclude 'id' as it's an identifier and 'correct_answer' to prevent potential data leakage
numerical_base_features = ['question_length', 'cluster_label', 'tsne_x', 'tsne_y']
X_features = balanced_df[numerical_base_features].copy()

# 3. Expand 'question_embedding' list column into separate columns
# Ensure 'question_embedding' is a list of floats
if 'question_embedding' in balanced_df.columns:
    # Convert string representation of list to actual list using ast.literal_eval
    balanced_df['question_embedding'] = balanced_df['question_embedding'].apply(ast.literal_eval)

    # Use .tolist() to convert the Series of lists into a list of lists,
    # which pd.DataFrame can then expand into columns.
    embedding_df = pd.DataFrame(balanced_df['question_embedding'].tolist(), index=balanced_df.index)
    embedding_df.columns = [f'embedding_{i}' for i in range(embedding_df.shape[1])]
    X_features = pd.concat([X_features, embedding_df], axis=1)

# 4. One-hot encode categorical features
categorical_cols_to_encode = ['approach', 'difficulty']
for col in categorical_cols_to_encode:
    if col in balanced_df.columns:
        # Ensure the column is of string type for get_dummies to work correctly
        temp_col = balanced_df[col].astype(str)
        dummies = pd.get_dummies(temp_col, prefix=col, drop_first=True)
        X_features = pd.concat([X_features, dummies], axis=1)

# X is now X_features containing all selected and processed numerical features
X = X_features

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train a model (Random Forest example)
model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)

# Evaluate the model
y_pred = model.predict(X_test)
print("Acurácia:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

# Matriz de Confusão

In [ ]:
from sklearn.metrics import f1_score, roc_auc_score

print("F1:", f1_score(y_test, y_pred, average="weighted"))

In [ ]:
from sklearn.metrics import ConfusionMatrixDisplay
import matplotlib.pyplot as plt

ConfusionMatrixDisplay.from_predictions(y_test, y_pred)
plt.show()

## Interpretação da Matriz de Confusão

As **linhas** representam as classes **reais** (o `y_test`), ou seja, as categorias verdadeiras das questões. As **colunas** representam as classes **preditas** (o `y_pred`), ou seja, as categorias que o modelo atribuiu às questões.

Vamos detalhar essa matriz de confusão específica:

*   **'Ambiente de Negócios' (Real):**
    *   O modelo previu corretamente **93 questões** como 'Ambiente de Negócios' (verdadeiros positivos para esta classe).
    *   Ele não classificou erroneamente nenhuma questão de 'Ambiente de Negócios' como 'Pessoas' ou 'Processos' (zero falsos negativos).

*   **'Pessoas' (Real):**
    *   O modelo previu corretamente **94 questões** como 'Pessoas' (verdadeiros positivos).
    *   Ele classificou erroneamente **10 questões** que eram realmente 'Pessoas' como 'Processos' (falsos negativos).
    *   Ele não classificou erroneamente nenhuma questão como 'Ambiente de Negócios'.

*   **'Processos' (Real):**
    *   O modelo previu corretamente **89 questões** como 'Processos' (verdadeiros positivos).
    *   Ele classificou erroneamente **2 questões** que eram realmente 'Processos' como 'Pessoas' (falsos negativos).
    *   Ele não classificou erroneamente nenhuma questão como 'Ambiente de Negócios'.

### Principais Conclusões:

*   **Alta Precisão para 'Ambiente de Negócios':** O modelo teve um desempenho perfeito para esta classe, identificando corretamente todas as instâncias sem falsos positivos ou falsos negativos.
*   **Pequena Confusão entre 'Pessoas' e 'Processos':** A principal área de erro de classificação está entre os domínios 'Pessoas' e 'Processos'. O modelo ocasionalmente confundiu questões de 'Pessoas' com 'Processos', e vice-versa.
*   **Desempenho Geral Forte:** Os elementos da diagonal (previsões corretas) são significativamente maiores do que os elementos fora da diagonal (previsões incorretas), o que indica que seu modelo está com um desempenho muito bom em todas as classes, especialmente considerando o balanceamento do conjunto de dados.

# Identificar variáveis alvo

In [ ]:
import pandas as pd

df = pd.read_csv("/content/drive/MyDrive/2026/760_questions.csv")

print("=== Tipos de colunas ===")
print(df.dtypes)

print("\n=== Colunas categóricas e distribuição ===")
for col in df.select_dtypes(include=["object", "category"]).columns:
    print(f"\n--- {col} ---")
    print(df[col].value_counts())
    print(f"Desbalanceamento: {df[col].value_counts().max() / df[col].value_counts().min():.1f}x")